# **기존 AAN_new_PCA+XGB와의 차이점**
- AAN_new 데이터셋을 리뉴얼함.
- 리뉴얼 데이터셋으로 PCA + XGB 이용
- PCA 0.98로 이용

# **리뉴얼된 AAN_new**
- float64 데이터를 float32로 바꿈.
- 에러를 삽입할 때, 각 섹터에 순차적으로 넣는대신 random하게 고름




In [7]:
!pip install ipython-autotime
%load_ext autotime
import pandas as pd
import numpy as np
import os
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
import pickle
import math

# read data pickle
path = os.getcwd() + "/drive/My Drive/data/AAN_new"

x_train = pd.read_pickle(path + '/reset_NoError_whole_x_train.pickle')
print('=== Data Loaded: reset_NoError_whole_x_train.pickle ===')
y_train = pd.read_pickle(path + '/reset_NoError_whole_y_train.pickle')
print('=== Data Loaded: reset_NoError_whole_y_train.pickle ===')
x_test = pd.read_pickle(path + '/reset_NoError_whole_x_test.pickle')
print('=== Data Loaded: reset_NoError_whole_x_test.pickle ===')
y_test = pd.read_pickle(path + '/reset_NoError_whole_y_test.pickle')
print('=== Data Loaded: reset_NoError_whole_y_test.pickle ===')



The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
=== Data Loaded: reset_NoError_whole_x_train.pickle ===
=== Data Loaded: reset_NoError_whole_y_train.pickle ===
=== Data Loaded: reset_NoError_whole_x_test.pickle ===
=== Data Loaded: reset_NoError_whole_y_test.pickle ===
time: 4.31 s


In [0]:
x_train

time  P1.B2004  ...  attack.P3  error
0       2019-11-02 09:24:00+09:00    0.0311  ...          0      0
1       2019-11-02 09:24:01+09:00    0.0311  ...          0      0
2       2019-11-02 09:24:02+09:00    0.0311  ...          0      0
3       2019-11-02 09:24:03+09:00    0.0311  ...          0      0
4       2019-11-02 09:24:04+09:00    0.0311  ...          0      0
...                           ...       ...  ...        ...    ...
727193  2019-11-01 19:59:55+09:00    0.0998  ...          0      0
727194  2019-11-01 19:59:56+09:00    0.0998  ...          0      0
727195  2019-11-01 19:59:57+09:00    0.0998  ...          0      0
727196  2019-11-01 19:59:58+09:00    0.0998  ...          0      0
727197  2019-11-01 19:59:59+09:00    0.0998  ...          0      0

[727198 rows x 65 columns]

time: 163 ms


In [0]:
x_test

time  P1.B2004  ...  attack.P3  error
0       2019-11-01 20:00:00+09:00    0.0998  ...          0      0
1       2019-11-01 20:00:01+09:00    0.0998  ...          0      0
2       2019-11-01 20:00:02+09:00    0.0998  ...          0      0
3       2019-11-01 20:00:03+09:00    0.0998  ...          0      0
4       2019-11-01 20:00:04+09:00    0.0998  ...          0      0
...                           ...       ...  ...        ...    ...
181795  2019-10-30 03:11:55+09:00    0.0305  ...          0      0
181796  2019-10-30 03:11:56+09:00    0.0305  ...          0      0
181797  2019-10-30 03:11:57+09:00    0.0305  ...          0      0
181798  2019-10-30 03:11:58+09:00    0.0305  ...          0      0
181799  2019-10-30 03:11:59+09:00    0.0305  ...          0      0

[181800 rows x 65 columns]

time: 137 ms


In [0]:
x_train.dtypes

time          object
P1.B2004     float32
P1.B2016     float32
P1.B3004     float32
P1.B3005     float32
              ...   
attack         int64
attack.P1      int64
attack.P2      int64
attack.P3      int64
error          int64
Length: 65, dtype: object

time: 5.58 ms


In [8]:

num0=0 # 노말
num1=0 # 어택
for i in y_train["attack"]:
  if(i == 0):
    num0 = num0+1
  elif(i == 1):
    num1 = num1+1
print("<<train>>")
print('normal 수')
print(num0)
print('attack 수')
print(num1)
print("전체")
print(str(num0+num1))


num0=0 # 노말
num1=0 # 어택
for i in y_test["attack"]:
  if(i == 0):
    num0 = num0+1
  elif(i == 1):
    num1 = num1+1
print("")
print("<<test>>")
print('normal 수')
print(num0)
print('attack 수')
print(num1)
print("전체")
print(str(num0+num1))

<<train>>
normal 수
659695
attack 수
67503
전체
727198

<<test>>
normal 수
152888
attack 수
28912
전체
181800
time: 178 ms


In [9]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# features to learn
features = ['P1.B2004', 'P1.B2016', 'P1.B3004', 'P1.B3005',\
'P1.B4002', 'P1.B4005', 'P1.B400B', 'P1.B4022', 'P1.FCV01D',\
'P1.FCV01Z', 'P1.FCV02D', 'P1.FCV02Z', 'P1.FCV03D', 'P1.FCV03Z',\
'P1.FT01', 'P1.FT01Z', 'P1.FT02', 'P1.FT02Z', 'P1.FT03',\
'P1.FT03Z', 'P1.LCV01D', 'P1.LCV01Z', 'P1.LIT01', 'P1.PCV01D',\
'P1.PCV01Z', 'P1.PCV02D', 'P1.PCV02Z', 'P1.PIT01', 'P1.PIT02',\
'P1.TIT01', 'P1.TIT02', 'P2.24Vdc', 'P2.Auto', 'P2.Emgy',\
'P2.On', 'P2.SD01', 'P2.SIT01', 'P2.TripEx', 'P2.VT01e',\
'P2.VXT02', 'P2.VXT03', 'P2.VYT02', 'P2.VYT03', 'P3.LCP01D', \
'P3.LCV01D', 'P3.LH', 'P3.LL', 'P3.LT01', 'P4.HT_FD',\
'P4.HT_LD', 'P4.HT_PO', 'P4.HT_PS', 'P4.LD', 'P4.ST_FD',\
'P4.ST_LD', 'P4.ST_PO', 'P4.ST_PS', 'P4.ST_PT01', 'P4.ST_TT01',
]

#scaling
scaler = StandardScaler()
scaler.fit(x_train[features])
scaled_x_train = scaler.transform(x_train[features])
scaled_x_test = scaler.transform(x_test[features])

# PCA 적용
pca_model = PCA(n_components=35)
pca_model.fit(scaled_x_train)
train_pca = pca_model.transform(scaled_x_train)
test_pca = pca_model.transform(scaled_x_test)

print("original x_train: {}".format(str(x_train[features].shape)))
print("transformed x_train: {}".format(str(train_pca.shape)))
print("original x_test: {}".format(str(x_test[features].shape)))
print("transformed x_test: {}".format(str(test_pca.shape)))

original x_train: (727198, 59)
transformed x_train: (727198, 35)
original x_test: (181800, 59)
transformed x_test: (181800, 35)
time: 6.67 s


In [10]:
y_train = np.ravel(y_train)
y_test = np.ravel(y_test)

# Xgboost 학습
clf = xgb.XGBClassifier(objective='multi:softmax', num_class=2, learning_rate=0.1, 
                        max_depth=8, min_child_weight=10, gamma= 0, random_state=0)
clf.fit(train_pca, y_train, verbose =1)

y_pred = clf.predict(test_pca)

# accuracy score
acc = accuracy_score(y_test, y_pred)
print(acc*100, '\n')
# print confusion matrix
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))


#save model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
pickle.dump(clf, open(path + filename, "wb"))


# attack & error distribution
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))

87.91914191419143 

confusion matrix
[[151300   1588]
 [ 20375   8537]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93    152888
           1       0.84      0.30      0.44     28912

    accuracy                           0.88    181800
   macro avg       0.86      0.64      0.68    181800
weighted avg       0.88      0.88      0.85    181800

time: 361 ms


# **N**

# 5

In [12]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/N/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.68756875687569
confusion matrix
[[150878   2010]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93    152888
           1       0.81      0.30      0.43     28912

    accuracy                           0.88    181800
   macro avg       0.85      0.64      0.68    181800
weighted avg       0.87      0.88      0.85    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
504
normal error인데 normal으로 분류된 경우
7140
오분류 에러: 6.593406593406594
time: 4.35 s


10

In [13]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/N/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.46369636963696
confusion matrix
[[150471   2417]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93    152888
           1       0.78      0.30      0.43     28912

    accuracy                           0.87    181800
   macro avg       0.83      0.64      0.68    181800
weighted avg       0.86      0.87      0.85    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
1000
normal error인데 normal으로 분류된 경우
14288
오분류 에러: 6.541077969649398
time: 14.1 s


15

In [15]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/N/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.1974697469747
confusion matrix
[[149987   2901]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93    152888
           1       0.75      0.30      0.42     28912

    accuracy                           0.87    181800
   macro avg       0.81      0.64      0.68    181800
weighted avg       0.86      0.87      0.85    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
1562
normal error인데 normal으로 분류된 경우
21371
오분류 에러: 6.811145510835913
time: 12 s


30

In [18]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/N/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str((a/errors)*100)))




86.50935093509351
confusion matrix
[[148736   4152]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.92    152888
           1       0.67      0.30      0.41     28912

    accuracy                           0.87    181800
   macro avg       0.78      0.63      0.67    181800
weighted avg       0.85      0.87      0.84    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
3056
normal error인데 normal으로 분류된 경우
42810
오분류 에러: 6.662887541970086
time: 11.1 s


# **A1**

5

In [19]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




85.2040704070407
confusion matrix
[[146363   6525]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92    152888
           1       0.57      0.30      0.39     28912

    accuracy                           0.85    181800
   macro avg       0.72      0.63      0.65    181800
weighted avg       0.83      0.85      0.83    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
5017
normal error인데 normal으로 분류된 경우
2627
오분류 에러: 65.63317634746207
time: 7.23 s


10

In [21]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




82.54400440044004
confusion matrix
[[141527  11361]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90    152888
           1       0.43      0.30      0.35     28912

    accuracy                           0.83    181800
   macro avg       0.65      0.61      0.62    181800
weighted avg       0.80      0.83      0.81    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
9934
normal error인데 normal으로 분류된 경우
5354
오분류 에러: 64.97906855049712
time: 4.98 s


15

In [22]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




79.83608360836084
confusion matrix
[[136604  16284]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.89      0.88    152888
           1       0.34      0.30      0.32     28912

    accuracy                           0.80    181800
   macro avg       0.61      0.59      0.60    181800
weighted avg       0.79      0.80      0.79    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
14948
normal error인데 normal으로 분류된 경우
7985
오분류 에러: 65.18117995901103
time: 13.4 s


30

In [23]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




71.72002200220022
confusion matrix
[[121849  31039]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83    152888
           1       0.22      0.30      0.25     28912

    accuracy                           0.72    181800
   macro avg       0.54      0.55      0.54    181800
weighted avg       0.75      0.72      0.73    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
29939
normal error인데 normal으로 분류된 경우
15927
오분류 에러: 65.27493132167619
time: 16.3 s


# **A2**

5

In [24]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.85258525852585
confusion matrix
[[151178   1710]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93    152888
           1       0.83      0.30      0.44     28912

    accuracy                           0.88    181800
   macro avg       0.86      0.64      0.68    181800
weighted avg       0.87      0.88      0.85    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
204
normal error인데 normal으로 분류된 경우
7440
오분류 에러: 2.6687598116169546
time: 13.2 s


10

In [25]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.7981298129813
confusion matrix
[[151079   1809]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93    152888
           1       0.83      0.30      0.43     28912

    accuracy                           0.88    181800
   macro avg       0.85      0.64      0.68    181800
weighted avg       0.87      0.88      0.85    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
367
normal error인데 normal으로 분류된 경우
14921
오분류 에러: 2.4005756148613293
time: 9.97 s


15

In [26]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.71727172717272
confusion matrix
[[150932   1956]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93    152888
           1       0.81      0.30      0.43     28912

    accuracy                           0.88    181800
   macro avg       0.85      0.64      0.68    181800
weighted avg       0.87      0.88      0.85    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
596
normal error인데 normal으로 분류된 경우
22337
오분류 에러: 2.598874983648018
time: 10.1 s


30

In [27]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.54620462046205
confusion matrix
[[150621   2267]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93    152888
           1       0.79      0.30      0.43     28912

    accuracy                           0.88    181800
   macro avg       0.84      0.64      0.68    181800
weighted avg       0.87      0.88      0.85    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
1155
normal error인데 normal으로 분류된 경우
44711
오분류 에러: 2.5182052064710243
time: 17 s


# **A1 N**

5

In [28]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_N/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




84.27337733773376
confusion matrix
[[144671   8217]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91    152888
           1       0.51      0.30      0.37     28912

    accuracy                           0.84    181800
   macro avg       0.69      0.62      0.64    181800
weighted avg       0.82      0.84      0.82    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
6715
normal error인데 normal으로 분류된 경우
929
오분류 에러: 87.84667713239142
time: 6.42 s


10

In [29]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_N/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




80.55115511551155
confusion matrix
[[137904  14984]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.90      0.89    152888
           1       0.36      0.30      0.33     28912

    accuracy                           0.81    181800
   macro avg       0.62      0.60      0.61    181800
weighted avg       0.79      0.81      0.80    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
13544
normal error인데 normal으로 분류된 경우
1744
오분류 에러: 88.59236002093145
time: 11.1 s


15

In [30]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_N/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




76.92574257425743
confusion matrix
[[131313  21575]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.86    152888
           1       0.28      0.30      0.29     28912

    accuracy                           0.77    181800
   macro avg       0.57      0.58      0.58    181800
weighted avg       0.77      0.77      0.77    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
20215
normal error인데 normal으로 분류된 경우
2718
오분류 에러: 88.14808354772599
time: 13.6 s


30

In [31]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_N/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




65.93124312431243
confusion matrix
[[111325  41563]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.85      0.73      0.78    152888
           1       0.17      0.30      0.22     28912

    accuracy                           0.66    181800
   macro avg       0.51      0.51      0.50    181800
weighted avg       0.74      0.66      0.69    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
40465
normal error인데 normal으로 분류된 경우
5401
오분류 에러: 88.22439279640693
time: 10.7 s


# **A2 N**

5

In [32]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2_N/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




87.06985698569856
confusion matrix
[[149755   3133]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93    152888
           1       0.73      0.30      0.42     28912

    accuracy                           0.87    181800
   macro avg       0.81      0.64      0.67    181800
weighted avg       0.86      0.87      0.85    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
1621
normal error인데 normal으로 분류된 경우
6023
오분류 에러: 21.206174777603348
time: 8.08 s


10

In [33]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2_N/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




86.24202420242024
confusion matrix
[[148250   4638]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.92    152888
           1       0.65      0.30      0.41     28912

    accuracy                           0.86    181800
   macro avg       0.76      0.63      0.66    181800
weighted avg       0.84      0.86      0.84    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
3215
normal error인데 normal으로 분류된 경우
12073
오분류 에러: 21.029565672422816
time: 10.6 s


15

In [34]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2_N/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




85.35423542354236
confusion matrix
[[146636   6252]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92    152888
           1       0.58      0.30      0.39     28912

    accuracy                           0.85    181800
   macro avg       0.73      0.63      0.65    181800
weighted avg       0.83      0.85      0.83    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
4903
normal error인데 normal으로 분류된 경우
18030
오분류 에러: 21.379671216151397
time: 9.75 s


30

In [35]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A2_N/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




82.79537953795379
confusion matrix
[[141984  10904]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90    152888
           1       0.44      0.30      0.35     28912

    accuracy                           0.83    181800
   macro avg       0.66      0.61      0.63    181800
weighted avg       0.81      0.83      0.81    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
9777
normal error인데 normal으로 분류된 경우
36089
오분류 에러: 21.31644355295862
time: 13.7 s


# **A1 A2**

5

In [36]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




84.83223322332233
confusion matrix
[[145687   7201]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91    152888
           1       0.54      0.30      0.38     28912

    accuracy                           0.85    181800
   macro avg       0.71      0.62      0.65    181800
weighted avg       0.82      0.85      0.83    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
5687
normal error인데 normal으로 분류된 경우
1957
오분류 에러: 74.39822082679225
time: 12.1 s


10

In [37]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




81.76952695269527
confusion matrix
[[140119  12769]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.89    152888
           1       0.40      0.30      0.34     28912

    accuracy                           0.82    181800
   macro avg       0.64      0.61      0.62    181800
weighted avg       0.80      0.82      0.81    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
11343
normal error인데 normal으로 분류된 경우
3945
오분류 에러: 74.19544740973313
time: 11.1 s


15

In [38]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




78.7106710671067
confusion matrix
[[134558  18330]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.87    152888
           1       0.32      0.30      0.31     28912

    accuracy                           0.79    181800
   macro avg       0.59      0.59      0.59    181800
weighted avg       0.78      0.79      0.78    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
16980
normal error인데 normal으로 분류된 경우
5953
오분류 에러: 74.0417738629922
time: 13.7 s


30

In [39]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




69.49339933993399
confusion matrix
[[117801  35087]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.85      0.77      0.81    152888
           1       0.20      0.30      0.24     28912

    accuracy                           0.69    181800
   macro avg       0.52      0.53      0.52    181800
weighted avg       0.75      0.69      0.72    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
33968
normal error인데 normal으로 분류된 경우
11898
오분류 에러: 74.05921597697642
time: 17.1 s


# **A1 A2 N**

5

In [40]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2_N/reset_Error_whole_x_test_5percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




84.53685368536854
confusion matrix
[[145150   7738]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91    152888
           1       0.52      0.30      0.38     28912

    accuracy                           0.85    181800
   macro avg       0.70      0.62      0.64    181800
weighted avg       0.82      0.85      0.83    181800

error 갯수
7644
normal error인데 attack으로 분류된 경우
6228
normal error인데 normal으로 분류된 경우
1416
오분류 에러: 81.4756671899529
time: 9.67 s


10

In [41]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2_N/reset_Error_whole_x_test_10percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




81.13201320132013
confusion matrix
[[138960  13928]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.91      0.89    152888
           1       0.38      0.30      0.33     28912

    accuracy                           0.81    181800
   macro avg       0.63      0.60      0.61    181800
weighted avg       0.79      0.81      0.80    181800

error 갯수
15288
normal error인데 attack으로 분류된 경우
12497
normal error인데 normal으로 분류된 경우
2791
오분류 에러: 81.74385138670853
time: 7.58 s


15

In [42]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2_N/reset_Error_whole_x_test_15percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




77.77117711771177
confusion matrix
[[132850  20038]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87    152888
           1       0.30      0.30      0.30     28912

    accuracy                           0.78    181800
   macro avg       0.58      0.58      0.58    181800
weighted avg       0.78      0.78      0.78    181800

error 갯수
22933
normal error인데 attack으로 분류된 경우
18695
normal error인데 normal으로 분류된 경우
4238
오분류 에러: 81.52008023372433
time: 8.64 s


30

In [43]:
picklename = os.getcwd() + "/drive/My Drive/data/AAN_new/A1_A2_N/reset_Error_whole_x_test_30percent.pickle"
x_test = pd.read_pickle(picklename)

# 스케일링
scaled_x_test = scaler.transform(x_test[features])
# PCA 적용
pca_x_test = pca_model.transform(scaled_x_test)

#load model
path = F"/content/drive/My Drive/data/model/"
filename = 'AAN_new_final_PCA+XGB.pkl'
loaded_model = pickle.load(open(path+ filename, "rb"))
y_pred = loaded_model.predict(pca_x_test)

print("")
acc = accuracy_score(y_test, y_pred)
print(acc*100)
print('confusion matrix')
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
# prediction 값.
df = pd.DataFrame(data=y_pred, columns=["attack"])
a = 0
b = 0
errors=0
for i, row in enumerate(x_test["error"]):
  if(row==1):
    errors = errors+1
    if(df.iloc[i].item()==1): # normal error인데 attack으로 분류된 경우.
      a=a+1
    elif(df.iloc[i].item()==0):  #normal error인데 normal으로 분류된 경우.
      b=b+1
print('error 갯수')
print(errors)
print('normal error인데 attack으로 분류된 경우')
print(a)
print('normal error인데 normal으로 분류된 경우')
print(b)
print('오분류 에러: {}'.format(str(a/errors*100)))




67.65951595159517
confusion matrix
[[114467  38421]
 [ 20374   8538]]
              precision    recall  f1-score   support

           0       0.85      0.75      0.80    152888
           1       0.18      0.30      0.23     28912

    accuracy                           0.68    181800
   macro avg       0.52      0.52      0.51    181800
weighted avg       0.74      0.68      0.70    181800

error 갯수
45866
normal error인데 attack으로 분류된 경우
37309
normal error인데 normal으로 분류된 경우
8557
오분류 에러: 81.34347882963415
time: 15.7 s
